defaults:
  - data: utkface_corrupt
  - model: resnet50
  - method: psc
  - _self_

seed: 42
device: cuda

paths:
  data_root: datasets
  checkpoint_dir: checkpoints
  source_dir: checkpoints/source
  source_model: null
  feature_stats: null
  raw_features: null
  act_stats: null

run:
  stage: adapt
  save_model: false
  train_mode: true

train:
  epochs: 100
  optimizer:
    params: all
    name: Adam
    lr: 1.0e-4
    weight_decay: 5.0e-4

stats:
  save_raw_features: false

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${method.name}_${data.name}
